version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo17@2024
      POSTGRES_DB: postgres
    restart: always 
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - odoo-network

  odoo17:
    container_name: web
    image: odoo:17
    depends_on:
      - postgres
    ports:
      - "10016:8069"
      - "20016:8072" # live chat
    tty: true
    command: --
    environment:
      - HOST=postgres
      - USER=odoo
      - PASSWORD=odoo17@2024

      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo17@2024
      - POSTGRES_DB=postgres
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
      # - ./entrypoint.sh:/entrypoint.sh   # if you want to install additional Python packages, uncomment this line!
      - ./odoo-addons:/mnt/extra-addons
      - ./odoo-config:/etc/odoo
      - ./odoo-data:/var/lib/odoo
    restart: always     
    networks:
      - odoo-network        # run as a service
    
  frontend:
    build:
      context: ./next-app
    container_name: next-app
    working_dir: /app
    # Set environment variables based on the .env file
    env_file:
      - .env
    volumes:
      - ./next-app/src:/app/src
      - ./next-app/public:/app/public
    restart: always
    ports:
      - "3000:3000"
    # command: npm start
    networks:
      - odoo-network

  nginx:
    image: nginx:latest
    container_name: odoo-nginx
    ports:
      - "80:80"
    volumes:
      - staticbuild:/app/public
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      # - react-app
      - odoo17
    networks:
      - odoo-network

    

volumes:
  odoo-addons:
  odoo-config:
  odoo-data:
  postgres-data:
  staticbuild:

networks:
  odoo-network:
    driver: bridge